server:
  port: 9091

springdoc:
  show-actuator: true
  packagesToScan: net.linkednest.www.controller

jwt:
  secret:
    key: QWR@EDDF%$W^%56SDFG#*XCVFGJ%#$%234adfgsdfbcvbsdWERGEFSDFGD!QWR@EDDF%$W^%56SDFG#*XCVFGJ%#$%234adfgsdfbcvbsdWERGEFSDFGD!

mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/testproj
      # jdbc-url: jdbc:mariadb://localhost:3306/test
      username: root
      password : in2299in
      # password: asdf1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#      ddl-auto: create

logging:
  level:
    org:
      springframework:
        web: DEBUG
    jdbc:
      sqlonly: fatal
      sqltiming: off
      resultsettable: off
      audit: off
      resultset: off
      connection: fatal

