spring:
  config:
    activate:
      on-profile: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://aws.connect.psdb.cloud/test?sslMode=VERIFY_IDENTITY
      username: vfv6yrl76p8btqsf6got
      password: pscale_pw_cNHTKWS0DuR95YtNxWukjvjjpMrnZ2DNUXBM6nLqqxv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thumbnail:
    uploadpath: /Users/leejinwon/www/board/uploadfiles
    domain:  http://127.0.0.1:8080/board
    path: /resources/uploadfiles/
  jackson:
    serialization:
      fail-on-empty-beans: false





