server:
  port: 9091

spring-doc:
  show-actuator: true
  packagesToScan: net.linkednest.www.controller, net.linkednest.backoffice.controller
  swagger:
    disable-swagger-default-url: false
    display-query-params-without-oauth2: true
    title: Test Project API Document
    description: API Document For Test Project
    version: v0.1

jwt:
  secret:
    key: QWR@EDDF%$W^%56SDFG#*XCVFGJ%#$%234adfgsdfbcvbsdWERGEFSDFGD!QWR@EDDF%$W^%56SDFG#*XCVFGJ%#$%234adfgsdfbcvbsdWERGEFSDFGD!

mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/test
      username: root
      password: asdf1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
  jdbc:
    sqlonly: fatal
    sqltiming: off
    resultsettable: off
    audit: off
    resultset: off
    connection: fatal

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    v2:
      key:
        site: 6LeqdfIlAAAAAPR4f8Ss4g-prgiuRmAOteyNDok0
        private: 6LeqdfIlAAAAABTCqccXaBnUatbGVkFbbOHrP--G
    v3:
      key:
        site: 6Leh2u4lAAAAAAQvtkg58iEDLK0HR0FDE5yBaOF4
        private: 6Leh2u4lAAAAAAcLQVTlpSbyCaFeGHFr-KKuXl0n

