[build]
  command = "npm run build:prod"
  publish = "front/build"
[[redirects]]
  from = "/api/*"
  to = "https://api.linkednest.site/api/:splat"  
  status = 200
  force = true
[[redirects]]
  from = "/user/*"
  to = "https://api.linkednest.site/user/:splat"  
  status = 200
  force = true  
[[redirects]]
  from = "/login"
  to = "https://api.linkednest.site/login/:splat"  
  status = 200
  force = true
[[redirects]]
  from = "/signup"
  to = "https://api.linkednest.site/signup/:splat"  
  status = 200
  force = true        
[[redirects]]
  from = "/tokenLogin"
  to = "https://api.linkednest.site/tokenLogin/:splat"  
  status = 200
  force = true      
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200      