[[redirects]]
  from = "/api/*"
  to = "https://api.linkednest.site/api/:splat"  
  status = 200
  force = true
[[redirects]]
  from = "/user"
  to = "https://api.linkednest.site/user"  
  status = 200

  force = true        
[[redirects]]
  from = "/user/*"
  to = "https://api.linkednest.site/user/:splat"  
  status = 200
  force = true  
[[redirects]]
  from = "/login"
  to = "https://api.linkednest.site/login"  
  status = 200
  force = true
[[redirects]]
  from = "/tokenLogin"
  to = "https://api.linkednest.site/tokenLogin"  
  status = 200
  force = true      
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200