name: Docker Image CI 

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  projectBuildAndDockerBuild:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout    
      uses: actions/checkout@v3

    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # gradle caching - 빌드 시간 향상
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # - name: Setup Gradle
    #   uses: gradle/gradle-build-action@v2

    - name: Set Yaml
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application-dev.yaml 
      env:
        spring.datasource:hikari.driver-class-name: org.mariadb.jdbc.Driver
        spring.datasource.hikari.jdbc-url: jdbc:mariadb://${{ secrets.DB_CONN_URL }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?useSSL=false 
        spring.datasource.hikari.username: ${{ secrets.DB_USERNAME }} 
        spring.datasource.hikari.password: ${{ secrets.DB_PASSWD }} 
    # gradle build
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --exclude-task test
      shell: bash  
    # - name: Docker meta
    #   id: docker_meta
    #   uses: crazy-max/ghaction-docker-meta@v1
    #   with:
    #     images: jwlee0208/linkednest_test
    #     tag-semver: |
    #       {{version}}
    #       {{major}}.{{minor}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64      
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}:github.v${{ github.run_number }}  #${{ steps.docker_meta.outputs.tags }} 
        labels: ${{ steps.docker_meta.outputs.labels }}

#  awsIAMAndSGAndDeploy:
#    runs-on: ubuntu-latest  
#    steps:
    # 4. IP 보안그룹에 추가
    - name: Get Github Actions IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    # 5. Bastion Host를 통한 ssh 원격 명령어 실행 및 배포
    - name: Deploy to EC2 via Bastion
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.AWS_EC2_BASTION_SSH_PRIVATE_KEY }}
        host: ${{ secrets.AWS_EC2_BASTION_HOST }}
        username: ubuntu
        script: |        
            ssh api-server1 'bash /home/ubuntu/build.sh'      
            ssh api-server2 'bash /home/ubuntu/build.sh' 
    # 6. IP 보안 그룹에서 제거
    - name: Remove Github Actions IP From Security Group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32            
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
