name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout    
      uses: actions/checkout@v3

    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: jwlee0208/linkednest_test
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}      
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64      
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }} 
        labels: ${{ steps.docker_meta.outputs.labels }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
